type Article {
  source: String!
  country: String
  exchange: String
  title: String!
  description: String!
  author: String
  url: String!
  company: String
}


type Query {
  allArticles: [Article!]
  getArticleByUrl(url: String!): [Article!]
}