# deno deploy deployment
name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: wipe out training data and everything else
        run: |
          rm -rf data example ref
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: dli-fauna-gql # the name of the project on Deno Deploy
          entrypoint: fauna.ts # the entrypoint to deploy